service: bookings-consumer
provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1

functions:
  stream_listener:
    handler: handler.listen
    role: ${ssm:${self:custom.stage}-bookings-stream-consumer-iam-role}
    events:
      - stream: ${ssm:${self:custom.stage}-dynamodb-bookings-stream}
    environment:
      DYNAMODB_USERS: ${ssm:${self:custom.stage}-dynamodb-users-table}
      SNS_NOTIFICATIONS_TOPIC: ${ssm:${self:custom.stage}-bookings-notifications-topic}

custom:
  stage: ${opt:stage, self:provider.stage}
